### ISSUE TITLE
Confirm_reset関連

### ISSUE THREAD

**Issue by manmen2414** [manmen2414/Mike_pack#3]
サーバー上でconfirm_resetからCarurusを64つgiveするコマンドを使用すると鯖からkickされる
![image](https://github.com/manmen2414/Mike_pack/assets/102225383/9a930a05-c0ea-47e0-ae09-6077edfcfe86)

![image](https://github.com/manmen2414/Mike_pack/assets/102225383/1287e41e-77c2-4607-b9cf-54cfd9f3f229)

**Comment by manmen2414** [comment]
+ChoboChoboFillが実行できない

**Comment by HardSmoothy** [comment]
原因：Giveコマンドの説明入力が、海外サイトを利用せいて生成したため全てUnicodeになっており、選択して実行したとしても文字数オーバー扱いになる。
